# Generated by Django 2.2.6 on 2019-10-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0008_auto_20191014_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pin.Resource'),
        ),
    ]
