# Generated by Django 2.2.6 on 2019-10-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0009_auto_20191015_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='main',
        ),
    ]
