# Generated by Django 2.2.6 on 2019-10-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0010_remove_pin_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='board.Board'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='sha1',
            field=models.CharField(db_index=True, max_length=42, null=True),
        ),
    ]
