# Generated by Django 2.2.6 on 2019-10-22 16:56

from django.db import migrations


def move_resource_data(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Pin = apps.get_model('pin', 'Pin')
    for pin in Pin.objects.all():
        if not pin.resource:
            continue
        pin.sha1 = pin.resource.sha1
        pin.source_file = pin.resource.source_file
        pin.source_file_url = pin.resource.source_file_url
        pin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0011_auto_20191020_1812'),
    ]

    operations = [
        migrations.RunPython(move_resource_data)
    ]
