# Generated by Django 2.2.6 on 2019-10-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0012_auto_20191022_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
