# Generated by Django 2.2.6 on 2019-11-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0015_auto_20191111_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='policy',
        ),
    ]
