/*
 * Users actions types
 */
export const USER_REQUEST_LOGIN = 'USER_REQUEST_LOGIN'
export const USER_REQUEST_LOGIN_SUCCESS = 'USER_REQUEST_LOGIN_SUCCESS'
export const USER_REQUEST_LOGIN_FAILURE = 'USER_REQUEST_LOGIN_FAILURE'

export const USER_REQUEST_REGISTER = 'USER_REQUEST_REGISTER'
export const USER_REQUEST_REGISTER_SUCCESS = 'USER_REQUEST_REGISTER_SUCCESS'
export const USER_REQUEST_REGISTER_FAILURE = 'USER_REQUEST_REGISTER_FAILURE'

export const USER_REQUEST_USER = 'USER_REQUEST_USER'
export const USER_REQUEST_USER_SUCCESS = 'USER_REQUEST_USER_SUCCESS'
export const USER_REQUEST_USER_FAILURE = 'USER_REQUEST_USER_FAILURE'

export const USER_REQUEST_VERIFY_TOKEN = 'USER_REQUEST_VERIFY_TOKEN'
export const USER_REQUEST_VERIFY_TOKEN_SUCCESS = 'USER_REQUEST_VERIFY_TOKEN_SUCCESS'
export const USER_REQUEST_VERIFY_TOKEN_FAILURE = 'USER_REQUEST_VERIFY_TOKEN_FAILURE'

export const USER_REQUEST_REFRESH_TOKEN = 'USER_REQUEST_REFRESH_TOKEN'
export const USER_REQUEST_REFRESH_TOKEN_SUCCESS = 'USER_REQUEST_REFRESH_TOKEN_SUCCESS'
export const USER_REQUEST_REFRESH_TOKEN_FAILURE = 'USER_REQUEST_REFRESH_TOKEN_FAILURE'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_STORE_TOKEN = 'USER_STORE_TOKEN'

export const USER_REQUEST_MEMBER = 'USER_REQUEST_MEMBER'
export const USER_REQUEST_MEMBER_SUCCESS = 'USER_REQUEST_MEMBER_SUCCESS'
export const USER_REQUEST_MEMBER_FAILURE = 'USER_REQUEST_MEMBER_FAILURE'


