# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_n_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update date'),
        ),
        migrations.AlterField(
            model_name='board',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='board_followers', to=settings.AUTH_USER_MODEL, verbose_name='Users who follow board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='users_can_read',
            field=models.ManyToManyField(blank=True, related_name='users_can_read', to=settings.AUTH_USER_MODEL, verbose_name='Users who can see board if private'),
        ),
    ]
