# Generated by Django 2.2.6 on 2019-11-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20191020_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private board'),
        ),
    ]
