# Generated by Django 2.2.6 on 2019-11-11 14:34

from django.db import migrations


def move_policy_to_private(apps, schema_editor):
     Board = apps.get_model('board', 'Board')
     for board in Board.objects.all():
        if board.policy == 1:
            board.private = False
        else:
            board.private = True
        board.save()


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_board_private'),
    ]

    operations = [
        migrations.RunPython(move_policy_to_private)
    ]
