# Generated by Django 2.2.6 on 2019-11-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20191111_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='policy',
        ),
    ]
